{
 "title": "lighthouse-influxDB-ssl-cpuThrottlling",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "query": "${VAR_BASE}" },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   },
   {
    "name": "site",
    "query": "SHOW TAG VALUES WITH KEY = \"site\""
   },
   {
    "name": "tag",
    "query": "SHOW TAG VALUES WITH KEY = \"tag\""
   },
   {
    "name": "page",
    "query": "SHOW TAG VALUES WITH KEY = \"page\""
   },
   {
    "name": "device",
    "query": "SHOW TAG VALUES WITH KEY = \"device\""
   },
   {
    "name": "netThrottling",
    "query": "SHOW TAG VALUES WITH KEY = \"netThrottling\""
   },
   {
    "name": "cpuThrottling",
    "query": "SHOW TAG VALUES WITH KEY = \"cpuThrottling\""
   },
   {
    "name": "iteration",
    "query": "SHOW TAG VALUES WITH KEY = \"iteration\""
   },
   { "name": "measurement", "query": "SHOW MEASUREMENTS" }
  ]
 },
 "panels": [
  {
   "title": "wiki global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$measurement test-ru.dom",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_page]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" },
        { "params": [ "site" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "$measurement all",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_site]] / [[tag_page]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" },
        { "params": [ "site" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "$measurement mean",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_site]] / [[tag_page]]",
       "measurement": "/^$measurement$/",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "wiki",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "cumulative-layout-shift test-ru.dom",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_page]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" },
        { "params": [ "site" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" }
       ],
       "measurement": "cumulative-layout-shift",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "cumulative-layout-shift  all",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_site]] / [[tag_page]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" },
        { "params": [ "site" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" }
       ],
       "measurement": "cumulative-layout-shift",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "compare sites pages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "site page filter",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]] [[tag_site]] / [[tag_page]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" },
        { "params": [ "site" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Run + Progress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runner",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "options": {
      "content": "<iframe src=\"https://fosemberg.sas.yp-c.test-ru.dom/website-performance-audit/static/index.html\" style=\"\r\n  width: 100%;\r\n  height: 100%;\r\n  border: 0;\r\n\"></iframe>"
     },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "progress percent",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_environment]] [[tag_site]] [[tag_tag]]",
       "groupBy": [
        { "params": [ "environment" ], "type": "tag" },
        { "params": [ "site" ], "type": "tag" },
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "progress",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "progressType", "operator": "=", "value": "percent" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" }
       ]
      }
     ]
    },
    {
     "title": "progress time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_environment]] [[tag_site]] [[tag_tag]]",
       "groupBy": [
        { "params": [ "environment" ], "type": "tag" },
        { "params": [ "site" ], "type": "tag" },
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "progress",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "progressType", "operator": "=", "value": "milliseconds" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "interactive mean",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "interactive",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "first-contentful-paint mean",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "first-contentful-paint",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "first-cpu-idle mean",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "first-cpu-idle",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "interactive mean filter",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]] [[tag_page]] [[tag_device]] [[tag_throttling]]",
       "groupBy": [
        { "params": [ "throttling" ], "type": "tag" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" },
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "interactive",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "first-contentful-paint mean filter",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]] [[tag_page]] [[tag_device]] [[tag_throttling]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "throttling" ], "type": "tag" }
       ],
       "measurement": "first-contentful-paint",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "first-cpu-idle mean filter",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]] [[tag_page]] [[tag_device]] [[tag_throttling]]",
       "groupBy": [
        { "params": [ "throttling" ], "type": "tag" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" },
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "first-cpu-idle",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "first-meaningful-paint mean",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "first-meaningful-paint",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "speed-index mean",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]]",
       "groupBy": [
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "speed-index",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "first-meaningful-paint mean filter",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]] [[tag_page]] [[tag_device]] [[tag_throttling]]",
       "groupBy": [
        { "params": [ "throttling" ], "type": "tag" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" },
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "first-meaningful-paint",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    },
    {
     "title": "speed-index mean filter",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "[[tag_tag]] [[tag_page]] [[tag_device]] [[tag_throttling]]",
       "groupBy": [
        { "params": [ "throttling" ], "type": "tag" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" },
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "speed-index",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "filter",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "iteration" ], "type": "tag" },
        { "params": [ "throttling" ], "type": "tag" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" },
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "filter",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "iteration" ], "type": "tag" },
        { "params": [ "netThrottling" ], "type": "tag" },
        { "params": [ "cpuThrottling" ], "type": "tag" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "page" ], "type": "tag" },
        { "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT \"value\" FROM /^$measurement$/ WHERE $timeFilter GROUP BY \"tag\", \"iteration\", \"throttling\", \"device\", \"page\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
        { "condition": "AND", "key": "tag", "operator": "=~", "value": "/^$tag$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" },
        { "condition": "AND", "key": "netThrottling", "operator": "=~", "value": "/^$netThrottling$/" },
        { "condition": "AND", "key": "cpuThrottling", "operator": "=~", "value": "/^$cpuThrottling$/" },
        { "condition": "AND", "key": "iteration", "operator": "=~", "value": "/^$iteration$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "FAQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "FAQ",
     "type": "text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "options": {
      "content": "#### The Time to Interactive (TTI)\r\nmetric measures how long it takes a page to become interactive. \"Interactive\" is defined as the point where:\r\n\r\n- The page has displayed useful content, which is measured with First Contentful Paint.\r\n- Event handlers are registered for most visible page elements.\r\n- The page responds to user interactions within 50 milliseconds.\r\n\r\nSome sites optimize content visibility at the expense of interactivity. This can create a frustrating user experience. The site appears to be ready, but when the user tries to interact with it, nothing happens.\r\n\r\n[link](https://developers.google.com/web/tools/lighthouse/audits/time-to-interactive)\r\n\r\n#### First Contentful Paint (FCP)\r\nmeasures the time from navigation to the time when the browser renders the first bit of content from the DOM. This is an important milestone for users because it provides feedback that the page is actually loading.\r\n\r\n[link](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint)\r\n\r\n\r\n#### First CPU Idle\r\nThe First CPU Idle metric measures when a page is minimally interactive:\r\n\r\n- Most, but maybe not all, UI elements on the screen are interactive.\r\n- The page responds, on average, to most user input in a reasonable amount of time.\r\n\r\n[link](https://developers.google.com/web/tools/lighthouse/audits/first-cpu-idle)\r\n\r\n#### First Meaningful Paint\r\nPage load is a key aspect of how a user perceives the performance of your page.\r\n\r\nThis audit identifies the time at which the user feels that the primary content of the page is visible.\r\n\r\n[link](https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint)\r\n\r\n#### Speed Index\r\nSpeed Index is a page load performance metric that shows you how quickly the contents of a page are visibly populated. The lower the score, the better.\r\n\r\n[link](https://developers.google.com/web/tools/lighthouse/audits/speed-index)"
     }
    }
   ]
  }
 ]
}